# Generated by Django 4.1.7 on 2023-03-16 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("body", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "post",
            },
        ),
    ]
