# Generated by Django 4.1.7 on 2023-03-16 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radionova", "0003_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 3, 16, 10, 13, 52, 160318),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime(2023, 3, 16, 10, 13, 58, 76855)
            ),
            preserve_default=False,
        ),
    ]
