# Generated by Django 4.1.7 on 2023-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radionova", "0005_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="spotlight",
            field=models.BooleanField(default=False),
        ),
    ]
