# Generated by Django 5.0.6 on 2024-05-31 21:02

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStreamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('full_width_banner', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('background', wagtail.images.blocks.ImageChooserBlock()), ('gradient_color', wagtail.blocks.CharBlock(required=False)), ('buttons', wagtail.blocks.StreamBlock([('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock(help_text='Link to a internal page (use eight this or the external url, not both.)', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Link to an external url (use either this or the page, not both.)', required=False))]))], max_num=1, min_num=0, required=False))])), ('horizontal_box_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock(help_text='Link to a internal page (use eight this or the external url, not both.)', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Link to an external url (use either this or the page, not both.)', required=False))])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('gradient_color', wagtail.blocks.CharBlock(help_text='Adds a gradient on top of the background image', required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))]))), ('walkthrough', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_background_color', wagtail.blocks.CharBlock())]))), ('buttons', wagtail.blocks.StreamBlock([('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock(help_text='Link to a internal page (use eight this or the external url, not both.)', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Link to an external url (use either this or the page, not both.)', required=False))]))], max_num=1, min_num=0, required=False))])), ('horizontal_section', wagtail.blocks.StreamBlock([('box_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock(help_text='Link to a internal page (use eight this or the external url, not both.)', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Link to an external url (use either this or the page, not both.)', required=False))])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('gradient_color', wagtail.blocks.CharBlock(help_text='Adds a gradient on top of the background image', required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))])), ('free_text', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=False))])), ('image_box', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))]))])), ('vertical_section', wagtail.blocks.StreamBlock([('box_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock()), ('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock(help_text='Link to a internal page (use eight this or the external url, not both.)', required=False)), ('external_url', wagtail.blocks.URLBlock(help_text='Link to an external url (use either this or the page, not both.)', required=False))])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('gradient_color', wagtail.blocks.CharBlock(help_text='Adds a gradient on top of the background image', required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))])), ('free_text', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=False))])), ('image_box', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))]))])), ('image_box', wagtail.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('background_color', wagtail.blocks.CharBlock(required=False))])), ('free_text', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=False))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FreeTextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
