# Generated by Django 4.1.7 on 2023-05-22 08:10

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tears", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="facts",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="headline",
            field=models.CharField(default="test headline", max_length=255),
            preserve_default=False,
        ),
    ]
