# Generated by Django 5.0.6 on 2024-05-31 21:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockstreampage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
    ]
