# Generated by Django 5.0.6 on 2024-05-31 21:12

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0003_alter_blockstreampage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockstreampage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=False))]))], blank=True),
        ),
    ]
