# Generated by Django 5.0.6 on 2024-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0011_programpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramPage',
        ),
    ]
