# Generated by Django 5.0.6 on 2024-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0013_program_organizers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='organizers',
            new_name='hosts',
        ),
    ]
