# Generated by Django 5.0.6 on 2024-06-13 20:38

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0016_programpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='description',
            field=wagtail.fields.StreamField([('main_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.blocks.RichTextBlock())], blank=True),
        ),
    ]
