# Generated by Django 5.0.6 on 2024-06-13 20:38

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0017_alter_programpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='description',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock())], blank=True),
        ),
    ]
