# Generated by Django 5.0.6 on 2024-06-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tears', '0018_alter_programpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='hosts',
        ),
        migrations.AlterField(
            model_name='programpage',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='BroadcastSchedule',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
