# Generated by Django 5.0.6 on 2024-09-25 16:43

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0019_remove_program_hosts_alter_programpage_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.RichTextBlock())], blank=True),
        ),
    ]
