# Generated by Django 5.0.6 on 2024-12-11 12:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0021_programmerpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmerpage',
            name='content',
        ),
        migrations.AddField(
            model_name='programmerpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
