# Generated by Django 5.0.6 on 2024-12-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0022_remove_programmerpage_content_programmerpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='author',
            new_name='redaksjon',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='forfatter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Forfatter'),
        ),
    ]
