# Generated by Django 5.0.6 on 2024-12-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0023_rename_author_blogpage_redaksjon_blogpage_forfatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, max_length=255, verbose_name='Foto:'),
        ),
    ]
