# Generated by Django 5.0.6 on 2024-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0024_blogpage_imagedecription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, max_length=255, verbose_name='BildeTekst:'),
        ),
    ]
