# Generated by Django 5.0.6 on 2025-02-03 17:41

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0025_alter_blogpage_imagedecription'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagTidPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('DagTidNavn', models.CharField(blank=True, max_length=255, verbose_name='DagTidNavn')),
                ('Rolle', models.CharField(blank=True, max_length=255, verbose_name='Rolle:')),
                ('beskrivelse', models.CharField(blank=True, max_length=255, verbose_name='beskrivelse:')),
                ('body', wagtail.fields.StreamField([('main_image', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
    ]
