# Generated by Django 5.0.6 on 2025-02-03 17:57

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0026_dagtidpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('AListeUke', models.CharField(blank=True, max_length=255, verbose_name='AListeUke')),
                ('date', models.DateTimeField(verbose_name='Post time')),
                ('Tittel', models.CharField(blank=True, max_length=255, verbose_name='Tittel:')),
                ('body', wagtail.fields.StreamField([('main_image', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.routable_page.models.RoutablePageMixin),
        ),
    ]
