# Generated by Django 5.0.6 on 2025-02-10 13:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0027_alistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='category',
            field=models.CharField(choices=[('aktualitet', 'Aktualitet'), ('humor_underholdning', 'Humor & underholdning'), ('kultur', 'Kultur'), ('musikk', 'Musikk'), ('tema', 'Tema'), ('tidligere_programmer', 'Tidligere programmer')], default='aktualitet', max_length=50),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='description',
            field=wagtail.fields.StreamField([('main_image', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
