# Generated by Django 5.0.6 on 2025-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0028_programpage_category_alter_programpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Introduksjon'),
        ),
    ]
