# Generated by Django 5.0.6 on 2025-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0030_programpage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alistpage',
            name='AListeUke',
        ),
        migrations.RemoveField(
            model_name='alistpage',
            name='Tittel',
        ),
        migrations.RemoveField(
            model_name='alistpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='alistpage',
            name='date',
        ),
        migrations.AddField(
            model_name='alistpage',
            name='image1',
            field=models.URLField(blank=True, help_text='First image URL from Facebook post'),
        ),
        migrations.AddField(
            model_name='alistpage',
            name='image2',
            field=models.URLField(blank=True, help_text='Second image URL from Facebook post'),
        ),
        migrations.AddField(
            model_name='alistpage',
            name='image3',
            field=models.URLField(blank=True, help_text='Third image URL from Facebook post'),
        ),
        migrations.AddField(
            model_name='alistpage',
            name='image4',
            field=models.URLField(blank=True, help_text='Fourth image URL from Facebook post'),
        ),
        migrations.AddField(
            model_name='alistpage',
            name='post_message',
            field=models.TextField(blank=True, help_text='Post message from Facebook'),
        ),
        migrations.AddField(
            model_name='alistpage',
            name='uke',
            field=models.TextField(blank=True, help_text='Which week it is', max_length=255),
        ),
    ]
