# Generated by Django 5.0.6 on 2025-03-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0033_dagtidpage_portrett_bilde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagtidpage',
            name='body',
        ),
    ]
