# Generated by Django 5.0.6 on 2025-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0036_alistapage_body_alter_alistapage_post_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='email_link',
            field=models.URLField(blank=True, verbose_name='E-post-link'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='Facebook-link'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='instagram_link',
            field=models.URLField(blank=True, verbose_name='Instagram-link'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='schedule_info',
            field=models.CharField(blank=True, help_text='F.eks: Mandager · 19:00 - 20:30', max_length=100, verbose_name='Sendetid'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='tiktok_link',
            field=models.URLField(blank=True, verbose_name='TikTok-link'),
        ),
    ]
