# Generated by Django 5.0.6 on 2025-04-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0037_programpage_email_link_programpage_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='redaksjon',
            new_name='user',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='tears.programpage', verbose_name='Program'),
        ),
    ]
