# Generated by Django 5.0.6 on 2025-04-28 14:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0038_rename_redaksjon_blogpage_user_blogpage_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dagtidpage',
            name='DagTidNavn',
        ),
        migrations.RemoveField(
            model_name='dagtidpage',
            name='Rolle',
        ),
        migrations.RemoveField(
            model_name='dagtidpage',
            name='beskrivelse',
        ),
        migrations.RemoveField(
            model_name='dagtidpage',
            name='portrett_bilde',
        ),
        migrations.AddField(
            model_name='dagtidpage',
            name='about_radio_nova',
            field=wagtail.fields.StreamField([('content', 0), ('main_image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, verbose_name='About Radio Nova'),
        ),
        migrations.AddField(
            model_name='dagtidpage',
            name='ansatte',
            field=wagtail.fields.StreamField([('ansatt', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Employee full name', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Their role/title', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Their email address', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('email', 2), ('image', 3)]], {})}, verbose_name='Ansatte (Employees)'),
        ),
        migrations.AddField(
            model_name='dagtidpage',
            name='omtaler_i_medier',
            field=wagtail.fields.StreamField([('omtale', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('description', 2), ('link', 3), ('image', 4)]], {})}, verbose_name='Omtaler i andre medier'),
        ),
    ]
