# Generated by Django 5.0.6 on 2025-04-29 13:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0039_remove_dagtidpage_dagtidnavn_remove_dagtidpage_rolle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='typeArticle',
            field=models.CharField(choices=[('article', 'Article'), ('anmeldelse', 'Anmeldelse'), ('intervju', 'Intervju')], default='article', max_length=50, verbose_name='Type of Article'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('more_images', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
