# Generated by Django 5.0.6 on 2025-04-29 16:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0040_blogpage_typearticle_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='imageDecription',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='ingress',
            field=models.CharField(blank=True, help_text='Kort ingress/underoverskrift under tittelen', max_length=500, verbose_name='Ingress'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 2), ('more_images', 2), ('content', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='tears.programpage', verbose_name='Redaksjon'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='typeArticle',
            field=models.CharField(choices=[('article', 'Artikkel'), ('anmeldelse', 'Anmeldelse'), ('intervju', 'Intervju')], default='article', max_length=50, verbose_name='Type of Article'),
        ),
    ]
