# Generated by Django 5.0.6 on 2025-04-29 16:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0041_remove_blogpage_imagedecription_blogpage_ingress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, max_length=255, verbose_name='BildeTekst:'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('more_images', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
