# Generated by Django 5.2.1 on 2025-05-13 12:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0043_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('more_images', 4), ('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Bildebeskrivelse', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, help_text='Bildebeskrivelse for hovedbilde', max_length=255, verbose_name='BildeTekst for Main_Bilde:'),
        ),
    ]
