# Generated by Django 5.2.1 on 2025-05-13 12:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0044_alter_blogpage_body_alter_blogpage_imagedecription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='imageDecription',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('more_images', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
