# Generated by Django 5.2.1 on 2025-05-13 12:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0045_remove_blogpage_imagedecription_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('more_images', 1), ('content', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
