# Generated by Django 5.2.1 on 2025-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0047_blogpage_imagedecription_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='overtittel',
            field=models.CharField(blank=True, help_text='Kort overtittel under hovedtittelen. For intervju er dette navnet på den som er intervjuet, for anmeldelse er det hva du anmelder (enten det er Film, Spisested eller Musikk), for artikkel er det en kort beskrivelse av hva artikkelen handler om.', max_length=500, verbose_name='Overtittel'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, help_text='BildeTekst under første bildet', max_length=255, verbose_name='BildeTekst:'),
        ),
    ]
