# Generated by Django 5.2.1 on 2025-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0048_blogpage_overtittel_alter_blogpage_imagedecription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='overtittel',
            field=models.CharField(blank=True, help_text='Kort overtittel under hovedtittelen. For intervju er dette navnet på den som er intervjuet, for anmeldelse er det hva du anmelder (enten det er Film, Spisested eller Musikk), for vanlig nettsak trengs det ikke å skrive noe', max_length=500, verbose_name='Overtittel'),
        ),
    ]
