# Generated by Django 5.2.1 on 2025-06-05 08:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0049_alter_blogpage_overtittel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_description', 1), ('content', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'text-xs text-gray-500 mt-0 mb-4', 'help_text': 'Beskrivelse under bildet', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
