# Generated by Django 5.2.1 on 2025-06-05 09:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0050_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alistapage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='alistapage',
            name='post_message',
        ),
        migrations.RemoveField(
            model_name='alistapage',
            name='uke',
        ),
        migrations.AddField(
            model_name='alistapage',
            name='album_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='alistapage',
            name='content',
            field=wagtail.fields.StreamField([('main_image', 0), ('content', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='alistapage',
            name='forfatter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Forfatter'),
        ),
        migrations.AddField(
            model_name='alistapage',
            name='ingress',
            field=models.TextField(blank=True, help_text='ingress'),
        ),
    ]
