# Generated by Django 5.2.1 on 2025-06-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0051_remove_alistapage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alistapage',
            name='album_images',
        ),
    ]
