# Generated by Django 5.2.1 on 2025-06-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0052_remove_alistapage_album_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alistapage',
            name='body',
        ),
    ]
