# Generated by Django 5.2.1 on 2025-06-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0053_remove_alistapage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='alistapage',
            name='dato',
            field=models.DateField(blank=True, help_text='Dato for A-lista', null=True, verbose_name='Dato'),
        ),
        migrations.AddField(
            model_name='alistapage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_lista_posts', to='tears.programpage', verbose_name='Redaksjon'),
        ),
    ]
