# Generated by Django 5.2.1 on 2025-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0054_alistapage_dato_alistapage_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='schedule_info',
        ),
        migrations.AddField(
            model_name='programpage',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programpage',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programpage',
            name='weekday',
            field=models.CharField(blank=True, choices=[('1', 'Mandag'), ('2', 'Tirsdag'), ('3', 'Onsdag'), ('4', 'Torsdag'), ('5', 'Fredag'), ('6', 'Lørdag'), ('7', 'Søndag')], max_length=1),
        ),
    ]
