# Generated by Django 5.2.1 on 2025-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0057_nettsakerarkiv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NettsakerArkiv',
        ),
    ]
