# Generated by Django 5.2.1 on 2025-09-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0058_delete_nettsakerarkiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='imageDecription',
            field=models.CharField(blank=True, help_text='Bildetekst under første bildet', max_length=255, verbose_name='Bildetekst på hovedbilde:'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='ingress',
            field=models.TextField(blank=True, help_text='Kort ingress/underoverskrift under tittelen', max_length=500, verbose_name='Ingress'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='overtittel',
            field=models.CharField(blank=True, help_text=" F.eks. '[Navn på festival]' eller '[Navn på artist]'.", max_length=500, verbose_name='Navn på det du andmelder/intervjuer.'),
        ),
    ]
