# Generated by Django 5.1.5 on 2025-09-15 16:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0059_alter_blogpage_imagedecription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeskjedFraDagtid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tittel')),
                ('text', wagtail.fields.StreamField([('text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, help_text='Innholdet som vises i panelet på dashbordet', verbose_name='Tekstinnhold')),
            ],
            options={
                'verbose_name': 'Beskjed fra dagtid',
                'verbose_name_plural': 'Beskjed fra dagtid',
            },
        ),
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Sorteringsrekkefølge')),
            ],
            options={
                'verbose_name': 'Manual Category',
                'verbose_name_plural': 'Manual Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Text Content', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Enter your text content here')),
            ],
            options={
                'verbose_name': 'Text Content',
                'verbose_name_plural': 'Text Content',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Kort beskrivelse av manualen')),
                ('content', wagtail.fields.StreamField([('rich_text', 0), ('quote', 1), ('code', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Tekst'}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'For kode eller kommandoer', 'label': 'Kode'})}, help_text='Hovedinnholdet i manualen')),
                ('order', models.IntegerField(default=0, help_text='Sorteringsrekkefølge innenfor kategori')),
                ('is_published', models.BooleanField(default=True, help_text='Synlig for brukere')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='tears.manualcategory')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuals',
                'ordering': ['category__order', 'category__name', 'order', 'title'],
            },
        ),
    ]
