# Generated by Django 5.2.1 on 2025-09-12 18:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0060_manualcategory_textcontent_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('quote', 4), ('code', 5), ('content', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'For forsiden'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'For kode eller kommandoer', 'label': 'Kode'}), 6: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
