# Generated by Django 5.1.5 on 2025-09-16 00:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0060_beskjedfradagtid_manualcategory_textcontent_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textcontent',
            options={'verbose_name': 'Varsling', 'verbose_name_plural': 'Varsling'},
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('quote', 1), ('code', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Tekst'}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'For kode eller kommandoer', 'label': 'Kode'})}, help_text='Hovedinnholdet i manualen'),
        ),
    ]
