# Generated by Django 5.2.1 on 2025-09-12 18:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0061_remove_manual_main_image_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('quote', 4), ('url', 5), ('date', 6), ('time', 7), ('datetime', 8), ('boolean', 9), ('choice', 10), ('page', 11), ('code', 12), ('content', 13)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'For forsiden'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 6: ('wagtail.blocks.DateBlock', (), {'label': 'Dato'}), 7: ('wagtail.blocks.TimeBlock', (), {'label': 'Tid'}), 8: ('wagtail.blocks.DateTimeBlock', (), {'label': 'Dato og tid'}), 9: ('wagtail.blocks.BooleanBlock', (), {'label': 'Avkrysning'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('option1', 'Alternativ 1'), ('option2', 'Alternativ 2')], 'label': 'Valg'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Side'}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'For kode eller kommandoer', 'label': 'Kode'}), 13: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
