# Generated by Django 5.1.5 on 2025-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0061_alter_textcontent_options_alter_textcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=models.TextField(blank=True, help_text='Enter your text content here'),
        ),
    ]
