# Generated by Django 5.2.1 on 2025-09-15 15:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0062_alter_blogpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeskjedFraDagtid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tittel')),
                ('text', models.TextField(verbose_name='Tekst')),
            ],
            options={
                'verbose_name': 'Beskjed fra dagtid',
                'verbose_name_plural': 'Beskjed fra dagtid',
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('quote', 4), ('url', 5), ('page', 6), ('content', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'For forsiden'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Side'}), 7: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
