# Generated by Django 5.1.5 on 2025-09-16 00:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0062_alter_textcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('quote', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Tekst'}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'})}, help_text='Hovedinnholdet i manualen'),
        ),
    ]
