# Generated by Django 5.1.5 on 2025-09-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0063_alter_textcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='overtittel',
            field=models.CharField(blank=True, help_text=" F.eks. '[Navn på festival]' eller '[Navn på artist]'.", max_length=500, verbose_name='Navn på det du andmelder/intervjuer'),
        ),
    ]
