# Generated by Django 5.2.1 on 2025-09-15 15:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0063_beskjedfradagtid_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beskjedfradagtid',
            name='text',
        ),
        migrations.AddField(
            model_name='beskjedfradagtid',
            name='content',
            field=wagtail.fields.StreamField([('content', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, help_text='Innholdet som vises i panelet på dashbordet', verbose_name='Tekstinnhold'),
        ),
    ]
