# Generated by Django 5.2.1 on 2025-09-15 15:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0064_remove_beskjedfradagtid_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beskjedfradagtid',
            name='content',
        ),
        migrations.AddField(
            model_name='beskjedfradagtid',
            name='text',
            field=wagtail.fields.StreamField([('text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, help_text='Innholdet som vises i panelet på dashbordet', verbose_name='Tekstinnhold'),
        ),
    ]
