# Generated by Django 5.1.5 on 2025-09-16 15:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0064_alter_blogpage_overtittel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('content', 4), ('flex_block', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image left / Text right'), ('image_right', 'Text left / Image right'), ('text_both', 'Text on both sides'), ('image_both', 'Image on both sides')]}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('layout', 5), ('left_text', 6), ('right_text', 6), ('left_image', 7), ('right_image', 7)]], {})}),
        ),
        migrations.AlterField(
            model_name='dagtidpage',
            name='about_radio_nova',
            field=wagtail.fields.StreamField([('content', 0), ('main_image', 1), ('flex_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image left / Text right'), ('image_right', 'Text left / Image right'), ('text_both', 'Text on both sides'), ('image_both', 'Image on both sides')]}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('layout', 2), ('left_text', 3), ('right_text', 3), ('left_image', 4), ('right_image', 4)]], {})}, verbose_name='About Radio Nova'),
        ),
    ]
