# Generated by Django 5.1.5 on 2025-09-30 12:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0065_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='description',
            field=wagtail.fields.StreamField([('image_with_description', 2), ('content', 3), ('flex_block', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image left / Text right'), ('image_right', 'Text left / Image right'), ('text_both', 'Text on both sides'), ('image_both', 'Image on both sides')]}), 5: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('layout', 4), ('left_text', 5), ('right_text', 5), ('left_image', 6), ('right_image', 6)]], {})}),
        ),
    ]
