# Generated by Django 5.2.1 on 2025-09-15 15:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0065_remove_beskjedfradagtid_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('content', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
