# Generated by Django 5.2.1 on 2025-09-15 16:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0066_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('quote', 1), ('code', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Tekst'}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Sitat'}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'For kode eller kommandoer', 'label': 'Kode'})}, help_text='Hovedinnholdet i manualen'),
        ),
    ]
