# Generated by Django 5.1.5 on 2025-10-08 23:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0066_alter_programpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('content', 4), ('flex_block', 8), ('quote', 11)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image left / Text right'), ('image_right', 'Text left / Image right'), ('text_both', 'Text on both sides'), ('image_both', 'Image on both sides')]}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('layout', 5), ('left_text', 6), ('right_text', 6), ('left_image', 7), ('right_image', 7)]], {}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Sitat'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "F.eks. '– Vilde Krohn'", 'label': 'Navn', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('quote', 9), ('attribution', 10)]], {})}),
        ),
    ]
