# Generated by Django 5.1.5 on 2025-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0067_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='include_in_overview',
            field=models.BooleanField(default=True, help_text='Fjern haken for å skjule dette programmet fra programoversikten', verbose_name='Inkluder i programoversikt?'),
        ),
    ]
