# Generated by Django 5.1.5 on 2025-10-23 12:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0070_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('main_image', 0), ('image_with_description', 3), ('content', 5), ('flex_block', 9), ('quote', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse under bildet', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('content', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image left / Text right'), ('image_right', 'Text left / Image right'), ('text_both', 'Text on both sides'), ('image_both', 'Image on both sides')]}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('layout', 6), ('left_text', 7), ('right_text', 7), ('left_image', 8), ('right_image', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Sitat'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "F.eks. '– Vilde Krohn'", 'label': 'Navn', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 11)]], {})}),
        ),
    ]
