# Generated by Django 5.0.6 on 2026-02-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0072_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='transistor_embed_url',
            field=models.URLField(blank=True, help_text='Lim inn Transistor embed-URL, f.eks. https://share.transistor.fm/e/frokost/playlist'),
        ),
    ]
