# Generated by Django 5.0.6 on 2026-02-20 20:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tears', '0072_alter_blogpage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BliMedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Bli med i Radio Nova', max_length=150)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('application_deadline', models.CharField(blank=True, help_text="F.eks. 'Søknadsfrist: 15. mars'", max_length=120)),
                ('application_button_text', models.CharField(blank=True, default='Søk nå', max_length=60)),
                ('application_url', models.URLField(blank=True)),
                ('about_title', models.CharField(blank=True, default='Hva gjør vi?', max_length=120)),
                ('about_body', wagtail.fields.RichTextField(blank=True)),
                ('roles_title', models.CharField(blank=True, default='Roller vi søker', max_length=120)),
                ('roles', wagtail.fields.StreamField([('role', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('faq_title', models.CharField(blank=True, default='Spørsmål og svar', max_length=120)),
                ('faq', wagtail.fields.StreamField([('qa', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
